import { Bot, CheckCircle2, Lightbulb, Layers } from "lucide-react";

function AISummary() {
  return (
    <div className="rounded-2xl border border-gray-800 bg-[#111827] p-6">

      <div className="flex items-center gap-3">
        <div className="rounded-xl bg-blue-600/20 p-3">
          <Bot className="text-blue-400" size={24} />
        </div>

        <div>
          <h2 className="text-2xl font-bold text-white">
            AI Repository Summary
          </h2>
          <p className="text-gray-400 text-sm">
            Generated by Forge AI
          </p>
        </div>
      </div>

      <div className="mt-6 rounded-xl bg-[#0F172A] p-5">
        <p className="text-gray-300 leading-8">
          This repository is a modern full-stack software engineering
          workspace built using a modular architecture. The project follows
          component-based development and separates frontend, backend and AI
          services for easier maintenance and scalability.
        </p>
      </div>

      <div className="grid md:grid-cols-3 gap-5 mt-6">

        <div className="rounded-xl bg-[#0F172A] p-5">

          <div className="flex items-center gap-2 mb-3">
            <Layers className="text-cyan-400" size={20} />
            <h3 className="text-white font-semibold">
              Tech Stack
            </h3>
          </div>

          <ul className="space-y-2 text-gray-400 text-sm">
            <li>• React</li>
            <li>• Tailwind CSS</li>
            <li>• FastAPI</li>
            <li>• PostgreSQL</li>
          </ul>

        </div>

        <div className="rounded-xl bg-[#0F172A] p-5">

          <div className="flex items-center gap-2 mb-3">
            <CheckCircle2 className="text-green-400" size={20} />
            <h3 className="text-white font-semibold">
              Strengths
            </h3>
          </div>

          <ul className="space-y-2 text-gray-400 text-sm">
            <li>• Modular Architecture</li>
            <li>• Clean Routing</li>
            <li>• Reusable Components</li>
            <li>• Secure Authentication</li>
          </ul>

        </div>

        <div className="rounded-xl bg-[#0F172A] p-5">

          <div className="flex items-center gap-2 mb-3">
            <Lightbulb className="text-yellow-400" size={20} />
            <h3 className="text-white font-semibold">
              AI Suggestions
            </h3>
          </div>

          <ul className="space-y-2 text-gray-400 text-sm">
            <li>• Add unit tests</li>
            <li>• Lazy-load pages</li>
            <li>• Improve API caching</li>
            <li>• Dockerize backend</li>
          </ul>

        </div>

      </div>

    </div>
  );
}

export default AISummary;